# This is a config for E2B sandbox template.
# You can use template ID (i7xcjypuboaq658c8pyi) or template name (ai-website-builder-v2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("ai-website-builder-v2") # Sync sandbox
# sandbox = await AsyncSandbox.create("ai-website-builder-v2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ai-website-builder-v2')

team_id = "d913e6ec-2ea3-4bd5-a3cc-f9e60d363dc8"
dockerfile = "e2b.Dockerfile"
template_name = "ai-website-builder-v2"
template_id = "i7xcjypuboaq658c8pyi"
